# Generated by Django 5.0 on 2023-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_diver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='name',
        ),
        migrations.AddField(
            model_name='creature',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creature',
            name='latin_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creature',
            name='species',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
