# Generated by Django 5.0 on 2024-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_alter_observation_date_observed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster', models.CharField(max_length=100, null=True)),
                ('coefficient', models.FloatField()),
            ],
            options={
                'ordering': ['coefficient'],
            },
        ),
        migrations.AlterModelOptions(
            name='creature',
            options={'ordering': ['category', 'species']},
        ),
        migrations.RemoveField(
            model_name='diver',
            name='user',
        ),
        migrations.AlterField(
            model_name='diver',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
