# Generated by Django 5.0 on 2024-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_booster_alter_creature_options_remove_diver_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='points',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
